# Copyright (c) 2022 Joshua Schmitt
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "🐍 Metrics"

on:
  push:
    branches:
      master
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  profile-metrics:
    runs-on: ubuntu-latest
    name: "📷 Profile Metrics"
    steps:
      - uses: jqshuv/metrics@latest
        name: "🧨 Generate Image"
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jqshuv
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Berlin
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 3
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_music: yes
          plugin_music_limit: 3
          plugin_music_mode: recent
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: ${{ secrets.SPOTIFY_USERNAME }}
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_poopmap: yes
          plugin_poopmap_token: ${{ secrets.POOPMAP_TOKEN }}
          plugin_poopmap_days: 7
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: jqshuv
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
