# Copyright (c) 2022 Joshua Schmitt
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "🐍 Metrics"

on:
  push:
    branches:
      master
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  profile-metrics:
    runs-on: ubuntu-latest
    name: "📷 Profile Metrics"
    steps:
      - uses: lowlighter/metrics@latest
        name: "🧨 Generate Image"
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jqshuv
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Berlin
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 3
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_poopmap: yes
          plugin_poopmap_token: ${{ secrets.POOPMAP_TOKEN }}
          plugin_poopmap_days: 7
          plugin_stock: yes
          plugin_stock_duration: 1d
          plugin_stock_interval: 5m
          plugin_stock_symbol: MSFT
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: jqshuv